@startuml
class Usuarios{
	Cadena nombre
	+ Tcorreo correo
	Cadena contraseña
	Entero carnet
	Cadena rol
	Fecha fechaRegistro
	Fecha fechaEliminacion[0..1]
}

class Laboratorios{
	+ Entero id
	Cadena nombre
	Boolean activo
	Fecha
	Fecha fechaRegistro
	Fecha fechaEliminacion[0..1]
}

class Equipos{
	+ Entero id
	Boolean activo
	Fecha fechaRegistro
	Fecha fechaEliminacion[0..1]
}


class Elementos{
	+ Cadena id
	Cadena nombre
	Boolean activo
	Cadena tipo
	Fecha fechaRegistor
	Fecha fechaEliminacion[0..1]
}

Elementos "1..*" <- "1" Equipos : tiene
Equipos "1..*" <- "1" Laboratorios : tiene
Elementos "1..*" <- "1" Usuarios : registra
@enduml
